/*
 Copyright (C) 2023 Frequency Team /
 */

#ifndef FFI_EXAMPLE_H_
#define FFI_EXAMPLE_H_

/* This file was automatically generated by cbindgen */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum {
  OK,
  Error,
} Status;

typedef struct {
  const unsigned int *values;
  int values_len;
  Status status;
} Data;

void print_c(const Data *input);

#endif /* FFI_EXAMPLE_H_ */
