/*
 Copyright (C) 2023 Frequency Team /
 */

#ifndef GRAPH_SDK_FFI_H_
#define GRAPH_SDK_FFI_H_

/* This file was automatically generated by cbindgen */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum {
  OK,
  Error,
} Status;

typedef struct {
  const unsigned int *values;
  int values_len;
  Status status;
} Data;

void print_c(const Data *input);

#endif /* GRAPH_SDK_FFI_H_ */
